digidem/comapeo-mobile

- package-lock.json
- package.json
- src/frontend/App.tsx
- src/frontend/contexts/LocationContext.tsx
- src/frontend/hooks/persistedState/createPersistedState.ts
Added expo location services.
Updated location context to use mmkv instead of async storage.
> Chore: expo location service

- src/frontend/contexts/LocationContext.tsx
> fix: location context typing

- src/backend/package-lock.json
- src/backend/package.json
This is only used for the rollup build script in the backend
> chore: move magic-string to backend dev deps

- tsconfig.json
was noticing lots of timeout/perf issues in my IDE related to TS. guessing it was also indexing the backend directory, which includes its own node modules and source code, causing slowdowns
We only need to include the frontend code, since the backend has its own tsconfig
> chore: update tsconfig to improve indexing performance

- src/backend/src/status.js
Fixes #113
After reload, the frontend is sending a `get-server-status` message,
which the nodejs process receives, and tries to send back the current
status. However this message back never reaches the frontend, likely due
to the way the RN bridge is re-created during a reload.
One fix that worked was to add a small delay when responding to
`get-server-status`, but analysing the logs showed that, from the nodejs
process perspective, the app is going into the background and back into
the foreground after the reload, and _after_ the `get-server-status`
message is received. The fix that this implements is to re-send the
server status whenever the app comes back into the foreground, this
seems to fix things because it seems like nodejs bridge messages sent
while the app is in the background …
> fix: fix freeze after hot reload / fast refresh

- src/frontend/Navigation/AppNavigator.tsx
- src/frontend/hooks/useLastSavedLocation.ts
- src/frontend/screens/MapScreen/index.tsx
Creates a react-query hook that retrieves the last known location (previously found in the location context).
> chore:created useLastSavedLocation()

- messages/en.json
- src/frontend/Navigation/ScreenGroups/AppScreens.tsx
- src/frontend/hooks/persistedState/createPersistedState.ts
- src/frontend/hooks/persistedState/usePersistedSettings.ts
- src/frontend/screens/Observation/InsetMapView.tsx
- src/frontend/screens/ObservationEdit/LocationView.tsx
- src/frontend/screens/Settings/AppSettings/CoordinateFormat.tsx
- src/frontend/screens/Settings/AppSettings/index.tsx
- src/frontend/sharedComponents/FormattedData.tsx
- src/frontend/sharedComponents/SelectOne.tsx
- src/frontend/sharedTypes.ts
Created screen for user to choose coordinate format
Created persisted setting state to save format and propagate throughout the app.
> Coordinate format

- src/frontend/hooks/useLocationProviderStatus.ts
- src/frontend/screens/MapScreen/index.tsx
updated the map to useLocationProviderStatus(), which use to be collocated in the location Context
> update map to use useLocationProviderStatus()

- README.md
Updates the docs in the README to improve onboarding experience. In the future we may move this to a separate document (e.g. `Contributing.md`) but this should suffice right now
> chore: update README with better onboarding instructions

- patches/react-native-svg-transformer+1.3.0.patch
was getting an error from patch-package when postinstall step ran
> chore: fix patch file for react-native-svg-transformer

- src/frontend/screens/ObservationsList/index.tsx
- src/frontend/sharedComponents/BottomSheetModal/index.tsx
- src/frontend/sharedComponents/CameraView.tsx
ESLint was complaining about these. We can remove these dependencies.
> chore: remove unnecessary dependencies from React hooks

- package-lock.json
`npm audit` showed a security issue on `@babel/traverse`. I don't think this issue affects us but I ran `npm audit fix @babel/traverse` to fix it in any case.
> chore: update @babel/traverse

- src/frontend/sharedComponents/HomeHeader.tsx
fixes error with gps pill import
> chore: fix gps pill import

- src/frontend/screens/ObservationEdit/index.tsx
Was looking into what I thought was a bug and happened to pass by this (not related to supposed bug though)
> fix: add missing hook dep in ObservationEdit

- messages/en.json
- src/frontend/Navigation/ScreenGroups/AppScreens.tsx
- src/frontend/screens/LocationInfoScreen.tsx
Closes #264. Should not affect the app in any way
> chore: rename GpsModal to LocationInfoScreen

- app.config.js
- eas.json
- package-lock.json
- package.json
- scripts/build-translations.js
copy of #325 (used for fixing history)
>  fix: properly configure eas github integration

- messages/en.json
- src/frontend/screens/ObservationsList/NoProjectWarning.tsx
- src/frontend/screens/ObservationsList/index.tsx
Adds a warning, warning the user that they will not be able to sync their observations if the user is not part of a project.
Closes #317
> chore: observation won't sync warning

- src/frontend/contexts/IntlContext.tsx
- src/frontend/hooks/persistedState/usePersistedLocale.ts
- src/frontend/lib/intl.ts
> chore: eliminate require cycle warning for intl-related code

- src/frontend/Navigation/Stack/AppScreens.tsx
- src/frontend/hooks/server/media.ts
- src/frontend/screens/Observation/PhotoPreviewModal.tsx
- src/frontend/screens/Observation/index.tsx
- src/frontend/screens/ObservationsList/ObservationListItem.tsx
- src/frontend/sharedComponents/PhotoAttachmentView.tsx
- src/frontend/sharedComponents/PhotoUnpreparedView.tsx
- src/frontend/sharedComponents/Thumbnail/MediaScrollView.tsx
- src/frontend/sharedTypes/navigation.ts
This PR is adding photo preview which is opened when you click a photo thumbnail. This PR closes #229 as there's no more work to do. 
Closes #229
> feat: observation photo thumbnail opens modal

- messages/en.json
- package-lock.json
- package.json
- src/frontend/Navigation/Drawer.tsx
- src/frontend/Navigation/Stack/AppScreens.tsx
- src/frontend/hooks/useDeviceInfo.ts
- src/frontend/screens/Settings/About.tsx
- src/frontend/screens/Settings/index.tsx
- src/frontend/sharedTypes/navigation.ts
Created About CoMapeo Screen
Also created a wrapper hook, that uses react query to wrap [react-native-device-info](https://www.npmjs.com/package/react-native-device-info)
> feat: About CoMapeo screen

- src/frontend/screens/AddPhoto.tsx
> fix: fix styling of cancel button on add observation photo screen

- package-lock.json
- package.json
- src/frontend/screens/MapScreen/ObservationMapLayer.tsx
> feat: color mapped observations by preset

- src/frontend/App.tsx
- src/frontend/contexts/IntlContext.tsx
- src/frontend/screens/Settings/AppSettings/LanguageSettings.tsx
Fixes #485 
---
Preview:
https://github.com/user-attachments/assets/5cec9f71-f616-477f-9d44-fb68b55d6231
> fix: navigate to app settings after changing language

- src/frontend/contexts/ActiveProjectContext.tsx
- src/frontend/hooks/server/projects.ts
> fix: stores previous project

- src/frontend/screens/ObservationsList/ObservationListItem.tsx
- src/frontend/sharedComponents/PhotoAttachmentView.tsx
closes #513 
Shows thumbnail images in observations list
> feat: show photo thumbnails in observation list
