metro.config.js, package-lock.json, package.json, scripts/build-backend.sh, src/backend/index.js, src/backend/message-port-like.js, src/backend/package-lock.json, src/backend/package.json, src/frontend/App.tsx, src/frontend/MessagePortLike.ts, yarn.lock
Note that this points to #3 
fixes and adjustments include:
- installation of rpc-reflector in the backend project (think this fixes the issues noted about not being able to remove unnecessary deps)
- separate implementations of MessagePortLike. this is because the nodejs-mobile `channel` extends different behaving classes based on the environment (Node's `EventEmitter` in the nodejs-mobile process but React Native's `EventEmitter` in the React Native runtime). Due to the different APIs and behaviors between the two, creating a shared implementation is not trivial and more overhead than necessary. thie PR updates the existing implementation to only be used for the server-side and created a separate one to handle the client side.
- updates to rpc-reflector to fix import and type issues
- …
=> some adjustments to rpc reflector integration

src/frontend/contexts/IntlContext.tsx, src/frontend/hooks/persistedState/createPersistedState.ts, src/frontend/hooks/persistedState/usePersistedLocale.ts, src/frontend/hooks/usePersistedState.ts
Updated persisted store to not be statically created. Previous implementation (which followed Mapeo Mobile), meant that the persisted store was being dynamically created. This dynamic creation meant that a context was still need to propagate the state to the rest of the app, going against zustand best practices.
While this will mean more refactoring, I think this will come with an obvious benefit of a more simplified code and persisted store implementation!
=> chore: update persisted state to follow best practices

scripts/build-backend.mjs, src/backend/package-lock.json, src/backend/package.json, src/backend/scripts/bundle-backend.mjs
Adds the option for minifying the backend bundle using https://github.com/egoist/rollup-plugin-esbuild#standalone-minify-plugin. Not enabled by default with this PR since it's helpful to not minify for debugging purposes, but we'll want to use this when creating actual distributed builds.
Basic testing saw the bundle size go from ~3 MB to ~1.5 MB
=> chore: add minification option for bundling backend

src/frontend/hooks/useLocation.ts, src/frontend/hooks/useLocationProviderStatus.ts
Fixes #126
This PR contains two potential approaches to monitoring location provider status:
1. polling the status at a fixed interval
2. listening for location updates and checking the status if an update has not been received after a fixed interval
This separates the provider status from the location (in the useLocation() hook), because the provider status is displayed in a different component within the UI to the location.
The two approaches both achieve the same thing, but may have different performance implications. My instinct is that polling will be the most performant, since it looks like checking status has a low overhead. If we are going to use this state in more than one component we might want to put this into react context, so that we only create one interval for polling, vs. …
=> feat: useLocationProviderStatus hook

src/frontend/hooks/useLocation.ts
the useCallback in the useLocation hook was missing a dependency (`distanceInterval`) which would have resulted in that option not being able to be changed in subsequent renders (granted, not something we are likely to ever do).
Also, of more consquence, we were using `debounceOptions` as a dependency for the `useCallback`, which since it was created from a spread, this would be a new variable for every render. This would have resulted in the watch position subscription being unsubscribed and re-attached on each render. The solution is to use the primitive values  as the dependencies.
=> fix: fix useCallback deps in useLocation hook

android/app/src/main/res/values/styles.xml
Fixes an issue where having a dark theme set for the OS causes native styes to be incompatible with the app styles (e.g. scrollbar color for scrollviews).
Once our app styles account for light vs dark themes, we can revert this change.
---
Preview (see right-hand side of images):
- Before:
- After:
=> ensure light theme is used for native styles

package-lock.json, package.json, src/frontend/hooks/persistedState/usePersistedDraftObservation/index.ts, src/frontend/hooks/server/media.ts, src/frontend/hooks/server/observations.ts, src/frontend/screens/ObservationEdit/SaveButton.tsx, src/frontend/sharedTypes.ts
Closes #119 
This PR implements the following query hooks:
- `useCreateBlobMutation()`: mutation that accepts a photo object (presumably coming from a observation draft) and saves it as a blob
- `useAttachmentUrlQueries()`: query that accepts a list of observation attachments and performs a query to get the http url for each of them
Perhaps out of scope, but this PR also uses `useCreateBlobMutation()` in the `SaveButton` implementation. `useAttachmentUrlQueries()` is currently not used anywhere.
=> implement query hooks for saving attachments and retrieving attachment urls

src/frontend/contexts/ProjectContext.tsx, src/frontend/hooks/useSyncState.ts
Closes #148 
Most of the work done by @gmaclennan - I just made some small adjustments. Currently not being used anywhere.
Questions:
- should the returned state also have a `status` field, similar to what's done for the [`LocalDiscoveryState`](https://github.com/digidem/CoMapeo-mobile/blob/ecc62135945d87c44f4f38ec8e0ca962e24b726e/src/frontend/contexts/LocalDiscoveryContext.tsx#L16)? wasn't sure if we need the same level of complexity when dealing with sync state in terms of dealing with lots of async handling, so didn't try to implement that for now
=> implement useSyncState hook

src/config.json
Replaces the broken token with a (temporary) public access token created via the org account
=> fix: update mapbox public access token

src/frontend/screens/ObservationEdit/DescriptionField.tsx
For saving notes to an observation, updated the function `updateObservationNotes` to `updateTags`.
Closes #207
=> fix:changes "updateObservationNotes" to "updateTags"

package-lock.json, package.json, src/frontend/sharedComponents/BottomSheet/Content.tsx, src/frontend/sharedComponents/Button.tsx
This change should have no user impact.
Notably, this new version changes how nested ternaries are indented. Other than the Prettier version bump, this is just a whitespace change.
=> chore: update Prettier to v3.2.5

src/backend/patches/@electron+asar+3.2.9+001+remove-original-fs-require.patch, src/backend/patches/README.md, src/backend/scripts/bundle-backend.mjs
Closes #204 
Was able to verify that the backend runs as expected after this change. Can also confirm that the bundled output now makes sure that patched code of interest solely relies on `fs` (see `nodejs-assets/index.js` after running `npm run build:backend`)
- line 5:
```js
import require$$0$3, { mkdirSync } from 'fs';
```
- lines 11440-11463 (module code from `@electron/asar`):
```js
const fs$9 = require$$0$3;
const promisifiedMethods = [
'lstat',
'mkdtemp',
'readFile',
'stat',
'writeFile'
];
const promisified = {};
for (const method of Object.keys(fs$9)) {
if (promisifiedMethods.includes(method)) {
promisified[method] = fs$9.promises[method];
} else {
promisified[method] = fs$9[method];
}
}
// To make it more like fs-extra
promisified.mkdirp = (dir) => fs$9.promises.mkdir(dir, { …
```
=> chore: patch @electron/asar to avoid issue with non-existent dependency

tsconfig.json
Adding this because it's not included when defining `strict: true`, but it's easily one of the more helpful options when it comes to avoiding runtime errors
https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess
=> chore: use noUncheckedIndexedAccess option in TSConfig

messages/en.json, src/frontend/Navigation/ScreenGroups/AppScreens.tsx, src/frontend/hooks/useLocation.ts, src/frontend/lib/utils.ts, src/frontend/screens/GpsModal.tsx, src/frontend/sharedComponents/DateDistance.tsx, src/frontend/sharedComponents/GpsPill.tsx, src/frontend/sharedComponents/HomeHeader.tsx
Closes #199
Mostly a direct port of the implementation from Mapeo Mobile, although a few adjustments are made to account for the differences in hooks.
---
Preview:
- Map screen (location services enabled):
- Map screen (location services disabled):
- GPS modal (location services enabled):
- GPS modal (location services disabled):
=> feat: add GPS pill and screen with GPS-related info

src/frontend/lib/utils.test.ts, src/frontend/lib/utils.ts
This change:
- Adds a basic test for this function
- Removes an unnecessary `leftPad` function (which caused an ESLint error)
=> chore: clean up `convertToUTM`

src/backend/src/node-rs-crc32-shim.js
We have a shim for `@node-rs/crc32`. It makes heavy use of bitwise operators, such as `>>>`.
This disables the `no-bitwise` ESLint rule for this file because we still want to use bitwise operators here.
=> chore: disable "no-bitwise" ESLint rule for CRC32 shim

.eslintrc.js
To quote [the rule's docs][0]:
> It's (subjectively) good practice to separate styles from the view layout, when possible
Though we might want to do this someday, now is not the time. Let's disable this rule to avoid hundreds of warnings.
[0]: https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-inline-styles.md
=> chore: disable "no inline styles" ESLint rule

.eslintrc.js, src/frontend/App.tsx, src/frontend/Navigation/AppNavigator.tsx, src/frontend/Navigation/ScreenGroups/DeviceNamingScreens.tsx, src/frontend/contexts/PhotoPromiseContext/index.tsx, src/frontend/contexts/ProjectContext.tsx, src/frontend/contexts/SecurityContext.tsx, src/frontend/hooks/useSyncState.ts, src/frontend/mockdata.ts, src/frontend/screens/AddPhoto.tsx, src/frontend/screens/AppPasscode/ConfirmPasscodeSheet.tsx, src/frontend/screens/AppPasscode/SetPasscode.tsx, src/frontend/screens/Observation/index.tsx, src/frontend/screens/Settings/CreateOrJoinProject/CreateProject/index.tsx, src/frontend/screens/Settings/ProjectSettings/YourTeam/ReviewAndInvite/index.tsx, src/frontend/sharedComponents/AddButton.tsx, src/frontend/sharedComponents/BottomSheetModal/index.tsx, src/frontend/sharedComponents/DeviceCard.tsx, src/frontend/sharedComponents/FormattedData.tsx, src/frontend/sharedComponents/List/ListItemIcon.tsx, src/frontend/sharedComponents/Loading.tsx, src/frontend/sharedComponents/Pill.tsx, src/frontend/sharedComponents/RoleWithIcon.tsx, src/frontend/sharedComponents/icons/CategoryIcon.tsx
This fixes several violations of [@typescript-eslint/no-unused-vars][0]. There are still several that I didn't feel comfortable changing, but these ones were easy to fix.
[0]: https://typescript-eslint.io/rules/no-unused-vars/
=> chore: fix 40 trivial "unused variables" lint violations

src/frontend/screens/Settings/CreateOrJoinProject/CreateProject/index.tsx
`boderColor` should be `borderColor`.
This fixes a type error.
=> chore: fix misspelled "border color" prop

src/frontend/screens/MapScreen/ObsevationMapLayer.tsx
_I recommend [reviewing this with whitespace changes disabled](https://github.com/digidem/comapeo-mobile/pull/279/files?w=1)._
Our `onPress` handler code was failing to import a type from `@rnmapbox/maps`.
This fixes that by moving the handler into the component directly, avoiding the need to import the type.
=> chore: fix type error in `ObservationMapLayer` component

src/backend/src/node-rs-crc32-shim.js
`~~initialState` is forbidden because `initialState` could be `null`. This fixes that by ensuring it's set.
=> chore: fix type error in CRC32 shim

.github/workflows/ci.yml, package.json, src/backend/package.json, src/backend/tsconfig.json
Towards https://github.com/digidem/CoMapeo-mobile/issues/56
Introduces a basic github action that runs on non-draft PRs. ~Currently only does typechecking for both backend and frontend.~
Does the following checks for now:
- all: formatting checks
- backend: type checks
- frontend: unit tests
ESLint (for all) and typechecking (for frontend) to be done as a follow-up
=> chore: add basic github workflow

README.md
We may want to address this in the future. For now, we should document that the `npm start` step is required.
=> docs: `npm start` is required to develop

messages/en.json, src/frontend/screens/MapScreen/GPSPermissions/GPSPermissionsEnabled.tsx
The rest of the translations that use an ellipsis are using the exact character and not 3 periods `.`. This updates a message string that was introduced with the tracks work to maintain consistency.
=> chore: update translation source to use ellipsis

package-lock.json, package.json, src/frontend/packageJson.test.ts
This test-only change ensures that `@mapeo` dependencies are good in the frontend's `package.json`.
=> chore: test that frontend dependencies match backend

src/frontend/sharedComponents/BottomSheetModal/index.tsx
At first this was going to be a PR to fix a misspelled prop, but then after some thought decided that it was better to remove it altogether. I don't think we will be using this prop anytime soon and if we do, it will be straightforward to reimplement
=> chore: remove unused prop from BottomSheetModal component

src/frontend/screens/ManualGpsScreen/index.tsx
Icon was removed in https://github.com/digidem/comapeo-mobile/pull/312 but this screen wasn't updated to import the replacement one
---
Preview:
=> fix: missing icon import for save button in manual GPS entry screen

package-lock.json, package.json
Noticed this build issue when running `npx expo run:android`:
```sh
Could not find method useDefaultAndroidSdkVersions() for arguments [] on project ':expo-eas-client' of type org.gradle.api.Project.
```
Running `npx expo install --fix` downgraded `expo-updates`, which seems to have resolved the issue for me.
=> chore: downgrade expo-updates to expected version

messages/en.json, scripts/build-backend.mjs, src/backend/index.js, src/backend/package-lock.json, src/backend/package.json, src/backend/src/app.js, src/frontend/hooks/server/mapStyleUrl.ts, src/frontend/screens/MapScreen/index.tsx, src/frontend/screens/Observation/InsetMapView.tsx
Closes #243 
Notes:
- decision tree for which map's style.json to serve (EDIT: when map initially loads/renders):
Remaining items:
```sh
NODEJS-MOBILE: exiting due to SIG_DFL handler for signal 11
```
```sh
backtrace:
#00 pc 000000000004e0f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180) (BuildId:   
#01 pc 00000000000050b8  /system/bin/app_process64 (art::SignalChain::Handler(int, siginfo*, void*)+1120) (BuildId:   
#02 pc 00000000000008b0  [vdso] (__kernel_rt_sigreturn)
#03 pc 0000000000118c3c  [anon:scudo:primary]
```
One thing to try next: upload same map to Mapeo Mobile and see if same crash happens.
EDIT: I'm no longer getting the crash for mysterious reasons...
=> feat: add support for custom offline maps

messages/en.json, src/frontend/Navigation/Stack/AppScreens.tsx, src/frontend/hooks/server/fields.ts, src/frontend/screens/Observation/FieldDetails.tsx, src/frontend/screens/Observation/index.tsx, src/frontend/screens/ObservationEdit/index.tsx, src/frontend/screens/ObservationFields/Question.tsx, src/frontend/screens/ObservationFields/QuestionLabel.tsx, src/frontend/screens/ObservationFields/SelectMultiple.tsx, src/frontend/screens/ObservationFields/SelectOne.tsx, src/frontend/screens/ObservationFields/TextArea.tsx, src/frontend/screens/ObservationFields/index.tsx, src/frontend/sharedComponents/FormattedData.tsx, src/frontend/sharedTypes/navigation.ts
Add observation fields to observation edit screen and displays observations fields when viewing an observation
=> Feat observation fields

src/frontend/App.tsx
Follow up to #334 which implemented a suggestion but forgot to update imports 😅
=> fix: fix location-related imports used by TaskManager.defineTask()

package-lock.json, package.json
Running `npx expo-doctor` showed that we had the incorrect sentry version installed.
=> chore: downgrade Sentry dep to Expo-compatible version

app.json
Addresses the SecureStore error I keep seeing in #370 . This PR disables Android's [Auto Backup](https://developer.android.com/identity/data/autobackup) feature which is basically a mechanism that allows you to store your app data via a Google Drive account so that you can restore apps and their data later or on another device. Expo enables this by default: https://docs.expo.dev/versions/v50.0.0/config/app/#allowbackup
I don't have the feature enabled on my devices, but seems like disabling the manifest value fixes the issue I was seeing with SecureStore being unable to decrypt the vault everytime I loaded a new dev client, so maybe there's some underlying thing that's not playing well with the module. 
In general, I don't think it's desirable for us to have the app enabled for this …
=> fix: disable android:allowBackup manifest option

src/frontend/sharedComponents/BottomSheetModal/index.tsx
the prop was defined but never used in the component when it should be passed to the library's BottomSheetModal `onDismiss` prop, like it's done in [Mapeo Mobile](https://github.com/digidem/mapeo-mobile/blob/0c0ebbb9ef2261e21cd1d1c8bd5ab2fe42017ea3/src/frontend/sharedComponents/BottomSheetModal/index.tsx#L121).
There are a few consumers of this component that specify the prop for things like cleanup, which would've led to some unexpected behavior without this fix.
=> fix: use onDismiss() prop in BottomSheetModal component

src/frontend/metrics/generateMetricsReport.test.ts, src/frontend/metrics/generateMetricsReport.ts
Metrics reports include screen dimensions (width & height). If the provided `screen` object has additional properties, we want to ignore them.
This will likely be the case for us, because we're probably going to use [`Dimensions.get`][0] which returns an object with extra properties.
This change filters those out and only keeps the provided `width` and `height`.
[0]: https://reactnative.dev/docs/dimensions#get
=> chore: only send screen width & height in metrics report

src/frontend/AppNavigator.tsx, src/frontend/lib/utils.ts, src/frontend/sharedComponents/ProjectInviteBottomSheet/index.tsx
Fixes #391 
Also fixes an issue with determining the name of the current route. The `isEditingScreen()` util (now removed completely) did not properly extract the route name for screens within the tab container (e.g. going to camera or observations list). This would've caused unexpected behavior in some cases, such as the invite sheet showing up while in the camera screen (which is not desired).
=> fix: fix navigation error after responding to invite

src/frontend/AppNavigator.tsx, src/frontend/sharedComponents/ProjectInviteBottomSheet/InviteSuccessBottomSheetContent.tsx
Follow up to #404 , which only fixed a portion of #391. This PR actually fixes the navigation action that's selected after accepting the invite. Should've properly tested this in the previous PR 🤦‍♂️  
There's a separate issue that was discovered which I think is outside the scope of this PR. Will document and address as a follow-up (EDIT: see https://github.com/digidem/comapeo-mobile/issues/406)
=> fix: fix navigation action after accepting invite

src/backend/package-lock.json, src/backend/package.json
After the recent update to `@mapeo/core@9.0.0-alpha.11` (in 5a94b7faf509d027a3d7f20b568662af531a2b05), we need a new default config to avoid a crash.
=> fix: update default config to fix startup crash

app.json, package-lock.json, package.json
On production builds the map was not rendering and showing a black screen. The error was identified as [useClearTextTraffic](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) needed to be enabled.
This PR uses expo [BuildProperties](https://docs.expo.dev/versions/latest/sdk/build-properties/) to enable it/
=> fix: Introduces CleartextTraffic permission

src/frontend/hooks/useSendMetrics.ts
`generateMetricsReport` is not a default export, so we shouldn't import it that way.
=> fix: use correct import for metrics report function

app.json, expo-config-plugins/targetArmArchsOnly.js, scripts/download-prebuilds.mjs
Closes #447 
Reduces the debug apk's size by almost half(!)
apk internals comparison (white left is before, white right is after, right green is differences):
=> chore: only target arm-based architectures (for now)

src/frontend/hooks/useOnBackgroundedAndForegrounded.ts
I forgot to add this dependency in bb201e0f80a4a3efab0e2f109278a48febbd4ffd.
We don't ever change this argument in practice, but this fixes a lint error. And if we ever *do* change it in the future, we'll be ready.
=> chore: fix missing dependency in "on backgrounded/foregrounded" hook

patches/README.md, patches/nodejs-mobile-react-native+18.17.7+006+fix-copying-x86-prebuilds.patch
See patch comments and readme entry for full explanation, but basically some nodejs-mobile-react-native gradle steps were trying to find native prebuild directories that didn't exist due to slight naming discrepancies. This adds a patch to the gradle file, which I think is an easier (and maybe more appropriate?) solution than updating the configuration for all of the prebuild repos that we manage.
The original context for this PR can be found in #446 , but basically this is a relatively non-urgent PR because we decided to only build for arm (will happen in a separate PR). however, i think this is still good to have because it's one of those things that very easy to forget in the future, in case we decide to revisit introducing intel builds
=> chore: properly detect and copy Intel-based native prebuilds when building apk

src/frontend/hooks/server/invites.ts
potentially avoids very subtle bugs caused by race conditions. prior to this change, the mutation is not waiting on the actual reject call to finish, which could lead to issues if the app code is - for example - rejecting an invitation and then refetching all of the invites with the expectation of the rejection being applied first
=> fix: fix useRejectInvite mutation

messages/en.json, src/frontend/screens/Settings/ProjectSettings/index.tsx
Closes #421 
Removes the list item because doesn't perform as of right now. This item will be introduced once there's a clearer idea of what the config screen should look like.
=> chore: remove config item in project settings screen (temporary)

src/frontend/screens/Settings/ProjectSettings/DeviceName/EditScreen.tsx
Fixes #434 
Root issue was not properly creating a press handler via react hook form, which meant that pressing the button essentially did nothing.
unrelated, but `handleSubmit` is kind of an unfortunate naming from them - probably would've benefited from being called something like `createSubmitHandler`
=> fix: fix submit button when editing device name

src/frontend/hooks/server/deviceInfo.ts
the `deviceType` field was added as part of the `deviceInfo` that can be retrieved and saved.
=> chore: specify deviceType field when setting device info

src/frontend/hooks/server/invites.ts, src/frontend/sharedComponents/ProjectInviteBottomSheet/index.tsx
a recent upgrade to `@mapeo/core` changed a couple of things about how invites are handled, most notably replacing the `projectPublicId` field with the `projectInviteId` field. This wasn't accounted for when upgrading to the core version that introduced that change, causing some invite-related code to be broken.
=> fix: update invites api usage to fix invite accept flow

src/frontend/App.tsx
I would like to experimentally [enable tracing for Sentry](https://docs.sentry.io/platforms/react-native/tracing/) in order to analyze what data is collected. 
I believe with our current setup this information will be collected:
- [App Start](https://docs.sentry.io/product/insights/mobile-vitals/#app-start): how long the app takes to start (both cold starts and warm starts)
- [Slow and Frozen Frames](https://docs.sentry.io/product/insights/mobile-vitals/#slow-and-frozen-frames): Whenever the frame rate in the app drops below 60fps, or if a frame is frozen for >700ms
- [Stall Tracking](https://docs.sentry.io/platforms/react-native/tracing/instrumentation/automatic-instrumentation/#stall-tracking): When the JavaScript event loop takes longer than expected to complete
- [Fetch/XML Request …
=> chore: enable Sentry tracing

src/frontend/App.tsx, src/frontend/__mocks__/expo-crypto.ts, src/frontend/metrics/getSentryUserId.test.ts, src/frontend/metrics/getSentryUserId.ts
I verified this with (1) automated tests (2) the following in the running app:
```javascript
// This logged the user ID we set.
Sentry.withScope(scope => {
console.log(JSON.stringify(scope.getUser()));
});
```
Closes #488.
=> chore: rotate Sentry user ID every month

src/frontend/Navigation/Drawer.tsx, src/frontend/sharedComponents/HomeHeader.tsx, src/frontend/sharedComponents/icons/DrawerMenuIcon.tsx
closes #486 
On the drawer menu, the hamburger icon's `onPress` was being activated when touching around the icon. I originally though it was the hitslop, but setting it to null did not did fix the problem. Converting the `TouchableNativeFeedback` to a `TouchableOpacity` seemed to solved the problem.
I also converted the styling so the consumer can control it. The two components have added styling to adjust for this.
=> fix: Drawer only closes on touch of menu icon

src/frontend/lib/ExhaustivenessError.test.ts, src/frontend/lib/ExhaustivenessError.ts, src/frontend/screens/Settings/ProjectSettings/YourTeam/SelectDevice.tsx, src/frontend/sharedComponents/DeviceCard.tsx, src/frontend/sharedComponents/DeviceNameWithIcon.tsx, src/frontend/sharedTypes/index.ts
The `<DeviceNameWithIcon>` component takes an optional `isConnected` prop. If it's missing, we treat the device as disconnected, which is not necessarily right.
This change inverts that, hiding the "Disconnected" text in these cases.
Fixes #493.
=> fix: hide "disconnected" for unknown device connection status

src/frontend/screens/MapScreen/index.tsx
Fixes #487 
Test instructions:
1. Open app to main map screen
2. Zoom in/out using pinch gestures
3. Observe scale bar change to account for zoom change when map is idle.
---
Preview:
https://github.com/user-attachments/assets/1b2700e5-e347-4848-9786-f69527a61f6b
=> fix: update map scale bar when zoom changes

src/frontend/hooks/server/media.ts
`UseQueryOptions` type was imported but not used.
=> chore: remove unused import

src/frontend/screens/Observation/index.tsx, src/frontend/screens/ObservationEdit/ThumbnailAndActionTab.tsx
Addresses a couple of type errors related to specifying a prop that doesn't exist for the `MediaScrollView` component.
=> chore: fix type issues related to non-existent audioRecordings prop

src/frontend/screens/ObservationEdit/SaveButton.tsx
The original implementation was doing `const project = useProject()` and was trying to access the returned value as a normal project api, which is incorrect because `project` is a react query object. This PR switches it to use `useActiveProject()` which can be used as the project api directly.
Editing an observation is not yet exposed in the UI, so this technically preemptively fixes an issue that could have been encountered otherwise.
=> fix: fix potential field access issue when editing observation

src/frontend/hooks/server/invites.ts
Fixes #492
Exposes another small issue where initially returning to the "Your Team" screen will show the newly added member but without their name. I believe this is an issue related to the backend due to the following sequence:
1. Device A invites Device B
2. Device B accepts invite from Device A and responds to Device A. Device B also starts updating its own database to add itself to the project (**this takes some time to finish**).
3. Device A receives response from Device B, refetches project's members
4. Device B finishes updating its own database. Starts syncing initial information with Device A
5. Device A receives device info information about Device B
In the preview attached, what's displayed in the "Your Team" screen is what's shown after (3). Notice that if you navigate away …
=> fix: refetch project members after receiving invite response

messages/en.json, src/frontend/Navigation/Drawer.tsx, src/frontend/Navigation/Stack/AppScreens.tsx, src/frontend/Navigation/Stack/index.tsx, src/frontend/screens/AppPasscode/ConfirmPasscodeSheet.tsx, src/frontend/screens/AppPasscode/InputPasscode.tsx, src/frontend/screens/AppPasscode/TurnOffPasscode.tsx, src/frontend/screens/AuthScreen.tsx, src/frontend/screens/Security/index.tsx
Fixes #490
Seems that getting the security context set up was already done prior to this.
Also adds UI fixes for:
- bottom sheet modal that appears when confirming the app passcode to set
- bottom sheet modal that appears when confirming to turn off app passcode
Testing instructions:
1. Open side drawer
2. Press `Security` list item
3. Press `App Passcode` list item
4. Press `Continue` button
5. Use input to create app passcode. Press `Next` button
6. Repeat (5)
7. Press `Save App Passcode` in bottom sheet modal
8. Unfocus - but do not close - the app (e.g. go to a different app, do gesture/press button to go to phone home screen, etc). Re-focus the app. The auth screen should appear and require inputting passcode. After entering passcode successfully, authscreen should disappear and you …
=> feat: expose app passcode setting

messages/en.json, src/frontend/contexts/IntlContext.tsx, src/frontend/screens/AppPasscode/EnterPassToTurnOff.tsx, src/frontend/screens/AppPasscode/InputPasscode.tsx, src/frontend/screens/AppPasscode/PasscodeIntro.tsx, src/frontend/screens/AppPasscode/SetPasscode.tsx, src/frontend/screens/AppPasscode/index.tsx
Stacked on #503 
Noticed that the UI in these screens was very different compared to other parts of the app with similar designs. Believe this is an artifact of porting over directly from Mapeo Mobile, which may have had slightly different design specifications, but I would like it to be more consistent with how other similar screens are implemented (namely action buttons docked to the bottom of the screen, consistent spacing, etc).
In terms of technical changes:
- uses the shared `ScreenContentWithDock` component for relevant screens to ensure uniformity and consistency
- fixes an issue with injecting rich formatting into specific parts of a translation string. this requires using the [defaultRichTextElements](https://formatjs.io/docs/react-intl/components#defaultrichtextelements) …
=> chore: make UI for app passcode settings screens more consistent with other parts of app

src/frontend/screens/Settings/CreateOrJoinProject/CreateProject/index.tsx
Fixes #518 
Forgot that we're updating the extension name of the config file when I initially implemented this 😅
Testing instructions:
1. Download config file mentioned in the notion issue onto the device.
2. Initiate project creation flow in app
3. Toggle advanced project settings and press import config button
4. Select config file from file picker
5. Press create project
6. Create observation. Notice categories are aligned with the imported config
---
Preview:
https://github.com/user-attachments/assets/e18907c9-541a-460e-91e7-45fce996f554
=> fix: fix extension name allowed for project config file when importing

messages/en.json, src/frontend/hooks/server/projects.ts, src/frontend/sharedComponents/BottomSheetModal/Content.tsx, src/frontend/sharedComponents/LeaveProjectModalContent/AlreadyOnProject.tsx, src/frontend/sharedComponents/LeaveProjectModalContent/LeaveProject.tsx, src/frontend/sharedComponents/LeaveProjectModalContent/index.tsx, src/frontend/sharedComponents/ProjectInviteBottomSheet/index.tsx
Adds leave project screens.
Added as a separate modal since it needed to be full screen.
We couldn't add the leave project screens as a nav screen because the invite modal is declarative and opens when there is an active invite and closes when there are no more active invites. Due to the architecture of modal, they always show up on top of the navigator. This means that the modal would show up on top of the leave project screens if they were part of the nav.
https://github.com/user-attachments/assets/f55ab30d-3fce-4d21-bbc6-90d5cbfb88b0
closes #162
=> Feat leave project

package-lock.json, scripts/download-prebuilds.mjs, src/backend/package-lock.json
chore: update crc-native to latest version
This updates our [crc-native prebuild][0] to the latest version of crc-native, 1.0.11[^1]. This will hopefully fix [#534].
[^1]: Technically, 1.0.12 [was committed][1] but not deployed to npm.
[0]: https://github.com/digidem/crc-native-nodejs-mobile
[1]: https://github.com/holepunchto/crc-native/commit/d68f29366adc4afc08388a7ba09ed5c23789a810
[#534]: https://github.com/digidem/comapeo-mobile/issues/534
=> chore: update crc-native to latest version

src/frontend/lib/intl.ts, src/frontend/screens/Settings/AppSettings/LanguageSettings.tsx
There were a couple of type errors related to deriving values from the intl-related json files. This addresses those issues and also updates the implementation for deriving the supported languages to be a little more efficient (fewer loops over potentially large in-memory data)
=> chore: fix type errors related to intl

src/frontend/contexts/PhotoPromiseContext/types.ts, src/frontend/hooks/persistedState/usePersistedDraftObservation/index.ts, src/frontend/hooks/persistedState/usePersistedDraftObservation/photosMethods.ts, src/frontend/lib/utils.ts, src/frontend/screens/Observation/index.tsx, src/frontend/sharedComponents/Editor/index.tsx, src/frontend/sharedComponents/MediaScrollView/PhotoThumbnail.tsx, src/frontend/sharedComponents/MediaScrollView/index.tsx, src/frontend/sharedComponents/PhotoUnpreparedView.tsx
Closes #549 
Updated the architecture of the photos and the media scroll view.
Previously, Mapeo did not have access to the types used in the back end. So the front end created the `SavedPhoto` Type. We ported this type over, but using this outdated type added a lot of complexity as we had to convert `Obervation.attachments` to this `SavedPhoto` type. Now that we have access to the backend types, I updated SavedPhoto to be `Observation["Attachments"]`. Now we no longer have to convert the type back an forth, which was causing confusing errors ans spaghetti code.
But this means that we had to convert all the component which used `Photo` (`type Photo = SavedPhoto & DraftPhoto`) or `SavedPhoto`. This PR converts those component, mainly media scroll view.
Media Scroll View now simply takes a …
=> fix: MediaScrollView shows saved photos

README.md
This is a requirement for the browserstack open source plan that offer free real device testing for open source projects.
=> core: add browserstack note to README

src/frontend/constants.ts
Fixes #552 
The invite bottom sheet is not supposed to show up when the person being invited is in the process of creating/editing an observation. The check we had for making sure this doesn't happen excluded the case of creating an observation and being in the editor screen.
Testing steps:
1. Device A creates project
2. Device B starts creating observation. Stop at the editor screen
3. Device A invites Device B to project. Note that Device B does not see the invite sheet
4. Device B either leaves or finishes the observation creation. Upon returning to the map, the invite sheet should display.
---
Preview:
https://github.com/user-attachments/assets/f1031ec5-4501-494c-a467-faa0b3ebce22
=> fix: prevent project invite sheet from showing during observation creation

src/frontend/hooks/server/media.ts
Comment was originally introduced to silence an error that has now been addressed since merging https://github.com/digidem/comapeo-mobile/pull/566
=> chore: address lint error caused by ts-expect-error

.github/workflows/ci.yml
Seems as good a time as ever to enable type checks in CI for frontend code, given that at the time of writing, running that check reports no errors!
=> chore: run types check for frontend code in CI
